apiVersion: v1
kind: Pod
metadata:
  name: zero-scaler
spec:
  containers:
    - name:  zero-scaler
      image: semars/k8s-zero-scaler:latest
      env:
      - name: SENTINELS
        value: sentinel-0.sentinel.redis.svc.cluster.local:5000,sentinel-1.sentinel.redis.svc.cluster.local:5000,sentinel-2.sentinel.redis.svc.cluster.local:5000
      - name: REDIS
        value: redis://$(SENTINELS)
      - name: BROKER
        value: $(REDIS)
      - name: LOCK
        value: $(REDIS)
      - name: DEFAULT_QUEUE
        value: $(REDIS)
      - name: RESULT_BACKEND
        value: $(REDIS)
      - name: REDIS_MASTER_NAME
        value: mymaster

