apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-pod-creation-notify-initcontainer
spec:
  rules:
  - name: add-pod-creation-notify-initcontainer
    match:
      resources:
        kinds:
        - Deployment
    mutate:
      patchStrategicMerge:
        spec:
          template:
            spec:
              initContainers:
              - name: pod-creation-notify
                image: curlimages/curl
                args: ["http://zero-scaler-svc.default.svc.cluster.local", "-H", "Content-Type: application/json", "-X", "POST", "-d", '{"name": "{{request.object.metadata.name}}", "kind": "{{request.kind.kind}}", "namespace": "{{request.object.metadata.namespace}}"}']
